import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Sparkles, Shield, Users, Zap } from "lucide-react";
import { SEO } from "../components/SEO";
import { SectionHeading } from "../components/SectionHeading";
import { FOUNDERS, NAP } from "../data/site";

const pillars = [
  { icon: Sparkles, title: "Bespoke, Not Templated", desc: "Every line of code is written for your problem. No white-label, no shortcuts, no copy-paste." },
  { icon: Users, title: "Founder-Led Delivery", desc: "Engagements are run by the founders themselves. No hand-off to juniors, no account managers." },
  { icon: Shield, title: "Zero-Defect Standards", desc: "Automated regression, unit/integration/E2E, accessibility, security. Coverage enforced at CI." },
  { icon: Zap, title: "SLA-Backed", desc: "Contractually-backed SLAs on availability, latency, and incident response for every engagement." },
];

export function About() {
  return <div className="site-page"><SEO title="About — Founder-Led Engineering Team | Kalpanaaa Software Solutions" description="Three founders. One playbook. Bespoke engineering across web, mobile, cloud, QA, RAG, and multi-agent systems. Bengaluru, India." canonical="https://kalpanaaasoftwaresolutions.in/about" />
    <section className="border-b border-line/70"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12 py-16 md:py-24"><SectionHeading as="h1" eyebrow="About" title="Founders-led. Engineering-first. Zero templates." description={`${NAP.name} is a Bengaluru-based bespoke engineering partner. Three founders. One delivery playbook. Contractually-backed SLAs across every engagement.`}/></div></section>
    <section className="py-16 md:py-20"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12"><SectionHeading eyebrow="Founders" title="The team running every engagement"/><div className="mt-10 grid gap-6 md:grid-cols-3">{FOUNDERS.map((founder, index)=><motion.div key={founder.name} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.05}} className="site-card rounded-2xl p-7"><div className="flex items-center justify-center w-24 h-24 rounded-full overflow-hidden bg-gradient-to-br from-brand to-brand-light mb-5 ring-2 ring-brand/20 ring-offset-2">{founder.image ? <img src={founder.image} alt={`${founder.name} profile photo`} className="w-full h-full object-cover object-top" onError={(e)=>{const el=e.currentTarget;el.style.display='none';if(el.parentElement){el.parentElement.innerHTML=`<span class="text-white font-display text-2xl font-extrabold">${founder.name.split(' ').map((t:string)=>t[0]).slice(0,2).join('')}</span>`;}}} /> : <span className="text-white font-display text-2xl font-extrabold">{founder.name.split(" ").map(token=>token[0]).slice(0,2).join("")}</span>}</div><h3 className="text-lg font-bold text-ink">{founder.name}</h3><p className="text-xs font-mono uppercase tracking-widest text-brand mt-1">{founder.role}</p><p className="mt-4 text-sm text-muted leading-relaxed">{founder.bio}</p><div className="mt-5 flex flex-wrap gap-1.5">{founder.focus.map((area)=><span key={area} className="pill px-2 py-1">{area}</span>)}</div></motion.div>)}</div></div></section>
    <section className="py-16 md:py-20 site-surface border-y border-line/70"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12"><SectionHeading eyebrow="Our principles" title="Why teams hire us" align="center"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{pillars.map((pillar,index)=><motion.div key={pillar.title} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.05}} className="site-card rounded-2xl p-6"><pillar.icon size={22} className="text-brand mb-4"/><h3 className="text-base font-bold text-ink mb-2">{pillar.title}</h3><p className="text-sm text-muted leading-relaxed">{pillar.desc}</p></motion.div>)}</div></div></section>
    <section className="py-16 md:py-20"><div className="max-w-3xl mx-auto px-6 md:px-8 lg:px-12 text-center"><p className="eyebrow justify-center">Engage us</p><h2 className="mt-4 font-display text-3xl md:text-4xl font-extrabold text-ink">Engage the team.</h2><p className="mt-3 text-muted">Free 30-minute discovery call. No obligation, no deck-shuffling.</p><Link to="/contact" className="button-primary mt-7 px-7 py-4 text-sm font-bold uppercase tracking-widest gap-2">Book discovery call <ArrowRight size={16}/></Link></div></section>
  </div>;
}
