import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, BookOpen, Brain, ShieldCheck, CloudCog } from "lucide-react";
import { SEO } from "../components/SEO";
import { SectionHeading } from "../components/SectionHeading";
import { VisualScene } from "../components/visuals/VisualScene";

const posts = [
  { category:"AI Engineering", title:"RAG Systems in Production: Accuracy Is an Engineering Problem", summary:"A practical framework for retrieval quality, chunking, reranking, evaluation, guardrails, and observability — the work required after a chatbot demo succeeds.", icon:Brain, href:"/services/rag-systems", tags:["RAG","pgvector","Evaluation"] },
  { category:"Engineering Standards", title:"What a Zero-Defect Release Process Actually Looks Like", summary:"From unit and integration tests to Playwright E2E, accessibility checks, SAST, load testing, and release gates: a practical delivery standard for business-critical systems.", icon:ShieldCheck, href:"/services/qa-testing", tags:["QA","Playwright","CI/CD"] },
  { category:"Cloud Infrastructure", title:"Designing for Reliability Before Your First Production Incident", summary:"The AWS, Docker, Terraform, monitoring, backup, and incident-response decisions that turn a prototype into an accountable production platform.", icon:CloudCog, href:"/services/cloud-devops", tags:["AWS","DevOps","Reliability"] },
];
export function Blog() {
  const itemList={"@context":"https://schema.org","@type":"Blog",name:"Kalpanaaa Software Solutions — Engineering Notes",description:"Practical notes on AI engineering, dependable software delivery, and cloud infrastructure.",publisher:{"@type":"Organization",name:"Kalpanaaa Software Solutions Pvt. Ltd."},blogPost:posts.map((post)=>({"@type":"BlogPosting",headline:post.title,description:post.summary}))};
  return <div className="site-page min-h-screen"><SEO title="Engineering Blog — Kalpanaaa Software Solutions (kalpanaaasoftwaresolutions.com)" description="Engineering notes from Kalpanaaa Software Solutions (kalpanaaasoftwaresolutions.com) on RAG systems, multi-agent automation, QA, cloud infrastructure, and software delivery." canonical="https://kalpanaaasoftwaresolutions.com/blog" jsonLd={itemList}/>
    <section className="relative overflow-hidden border-b border-line/70"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12 py-16 md:py-24 grid lg:grid-cols-[minmax(0,1fr)_minmax(430px,.9fr)] gap-10 items-center"><SectionHeading as="h1" eyebrow="Engineering notes" title="Ideas that survive production." description="Practical thinking on dependable delivery, AI engineering, security, and cloud architecture — for teams who need systems to work in the real world."/><VisualScene variant="research-index" title="A connected research index for engineering notes"/></div></section>
    <section className="py-20 md:py-28"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12 grid gap-6 md:grid-cols-3">{posts.map((post,index)=><motion.article key={post.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.07}} whileHover={{y:-5}} className="site-card group flex flex-col rounded-2xl overflow-hidden transition-shadow"><div className="p-8 bg-[linear-gradient(135deg,#e4f0ff,#fff)] border-b border-line"><post.icon size={42} className="text-brand"/></div><div className="p-7 flex flex-col flex-1"><p className="text-[10px] uppercase font-mono tracking-[.16em] text-brand">{post.category}</p><h2 className="mt-3 text-xl font-bold leading-snug text-ink">{post.title}</h2><p className="mt-3 text-sm leading-relaxed text-muted">{post.summary}</p><div className="mt-5 flex flex-wrap gap-1.5">{post.tags.map((tag)=><span key={tag} className="pill px-2.5 py-1">{tag}</span>)}</div><Link to={post.href} className="mt-7 inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-widest text-brand hover:underline">Explore capability <ArrowRight size={14}/></Link></div></motion.article>)}</div></section>
    <section className="pb-20"><div className="max-w-3xl mx-auto px-6 text-center"><BookOpen size={22} className="mx-auto text-brand"/><h2 className="mt-4 font-display text-3xl font-extrabold text-ink">More technical notes are coming.</h2><p className="mt-3 text-muted">The blog structure is live and search-ready. New posts can be added without changing the site architecture.</p></div></section>
  </div>;
}
