import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Mail, MapPin, Clock, CheckCircle2, ArrowRight, Loader2 } from "lucide-react";
import { SEO } from "../components/SEO";
import { SectionHeading } from "../components/SectionHeading";
import { SERVICES, NAP } from "../data/site";

export function Contact() {
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); setSubmitting(true); setTimeout(() => { setSubmitting(false); setSubmitted(true); }, 800); };
  const contactPageJsonLd = { "@context": "https://schema.org", "@type": "ContactPage", name: "Contact Kalpanaaaa Software Solutions", description: "Submit a project proposal request. Free 30-min discovery call. Response within 24 business hours.", mainEntity: { "@type": "Organization", name: NAP.name, email: NAP.email, address: { "@type": "PostalAddress", addressLocality: NAP.city, addressRegion: NAP.region, addressCountry: NAP.country } } };
  const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
    { "@type": "Question", name: "What is your engagement process?", acceptedAnswer: { "@type": "Answer", text: "30-minute discovery call → 1-page technical proposal → fixed-price or dedicated-pod contract → Sprint Zero (CI/CD, staging env, foundation) → iterative delivery with weekly demos → zero-risk handover with full IP transfer." } },
    { "@type": "Question", name: "What is the response SLA?", acceptedAnswer: { "@type": "Answer", text: "All proposal requests receive an initial response within 24 business hours. Active engagements include a critical-incident response commitment documented in the engagement contract." } },
    { "@type": "Question", name: "How is pricing structured?", acceptedAnswer: { "@type": "Answer", text: "Two options are available: (1) fixed-price milestone contracts for well-scoped v1 builds, and (2) a Dedicated Engineering Pod starting at INR 10,000/month for ongoing modernization work. Every project is custom-quoted against scope." } },
  ]};
  return <div className="site-page"><SEO title="Contact — Start Your Digital Transformation | Kalpanaaaa" description="Submit a project proposal to Kalpanaaaa Software Solutions. Free 30-minute discovery call. Response within 24 business hours." canonical="https://kalpanaaasoftwaresolutions.in/contact" jsonLd={[contactPageJsonLd, faqJsonLd]} />
    <section className="border-b border-line/70"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12 py-16 md:py-24"><SectionHeading as="h1" eyebrow="Get in touch" title="Let's build something great." description="Share your requirements. We will prepare a bespoke technical proposal tailored to your enterprise goals."/></div></section>
    <section className="py-16 md:py-20"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12 grid gap-10 lg:grid-cols-12">
      <div className="lg:col-span-5 space-y-5">
        <div className="site-card rounded-2xl p-6"><h3 className="text-sm font-bold uppercase tracking-widest text-ink mb-4">Direct inquiries</h3><div className="space-y-3 text-sm"><a href={`mailto:${NAP.email}`} className="flex items-center gap-3 text-muted hover:text-brand transition-colors"><Mail size={16} className="text-brand"/><span>{NAP.email}</span></a><div className="flex items-center gap-3 text-muted"><Clock size={16} className="text-brand"/><span>Response SLA: under 24 business hours</span></div><div className="flex items-center gap-3 text-muted"><MapPin size={16} className="text-brand"/><span>{NAP.city}, {NAP.region}, India</span></div></div></div>
        <div className="site-card rounded-2xl p-6"><h3 className="text-sm font-bold uppercase tracking-widest text-ink mb-4">What happens next</h3><ol className="space-y-3 text-sm text-muted"><li className="flex gap-3"><span className="font-mono text-brand">01</span>We acknowledge within 24h.</li><li className="flex gap-3"><span className="font-mono text-brand">02</span>30-minute discovery call.</li><li className="flex gap-3"><span className="font-mono text-brand">03</span>1-page technical proposal.</li><li className="flex gap-3"><span className="font-mono text-brand">04</span>Contract → Sprint Zero.</li></ol></div>
      </div>
      <div className="lg:col-span-7"><AnimatePresence mode="wait">{submitted ? <motion.div key="success" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="site-card rounded-2xl p-10 text-center border-brand/40"><div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-emerald-500/15 text-emerald-600 mb-5"><CheckCircle2 size={32}/></div><h3 className="font-display text-2xl font-bold text-ink">Proposal received.</h3><p className="mt-2 text-muted">We will respond within 24 business hours at <span className="text-brand font-mono">{NAP.email}</span>.</p></motion.div>
      : <motion.form key="form" initial={{opacity:0}} animate={{opacity:1}} onSubmit={handleSubmit} className="site-card rounded-2xl p-8 space-y-5">
        <div className="grid sm:grid-cols-2 gap-5"><div><label htmlFor="name" className="block text-xs font-semibold uppercase tracking-widest text-muted mb-2">Full name</label><input id="name" type="text" required placeholder="e.g. Gaurav Tripathi" className="w-full rounded-lg border border-line bg-white px-4 py-3 text-sm text-ink placeholder:text-muted focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand transition-all"/></div><div><label htmlFor="email" className="block text-xs font-semibold uppercase tracking-widest text-muted mb-2">Email address</label><input id="email" type="email" required placeholder="you@company.com" className="w-full rounded-lg border border-line bg-white px-4 py-3 text-sm text-ink placeholder:text-muted focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand transition-all"/></div></div>
        <div><label htmlFor="type" className="block text-xs font-semibold uppercase tracking-widest text-muted mb-2">Project type</label><select id="type" className="w-full rounded-lg border border-line bg-white px-4 py-3 text-sm text-ink focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand transition-all">{SERVICES.map((service)=><option key={service.slug} value={service.slug}>{service.title}</option>)}</select></div>
        <div><label htmlFor="message" className="block text-xs font-semibold uppercase tracking-widest text-muted mb-2">Project details</label><textarea id="message" required rows={5} placeholder="Goals, requirements, timeline, constraints..." className="w-full rounded-lg border border-line bg-white px-4 py-3 text-sm text-ink placeholder:text-muted focus:outline-none focus:border-brand focus:ring-1 focus:ring-brand transition-all resize-y"/></div>
        <button type="submit" disabled={submitting} className="button-primary px-7 py-4 text-sm font-bold uppercase tracking-widest gap-2 disabled:opacity-70">{submitting ? <Loader2 size={16} className="animate-spin"/> : <>Submit proposal request <ArrowRight size={16}/></>}</button>
      </motion.form>}</AnimatePresence></div>
    </div></section>
  </div>;
}
