import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { CheckCircle2, ArrowRight, ArrowLeft } from "lucide-react";
import { SEO } from "../components/SEO";
import { SectionHeading } from "../components/SectionHeading";
import { ServiceCard } from "../components/ServiceCard";
import { CaseStudyCard } from "../components/CaseStudyCard";
import { VisualScene } from "../components/visuals/VisualScene";
import { INDUSTRIES, SERVICES, CASE_STUDIES } from "../data/site";
const industryToServices: Record<string,string[]>={government:["web-engineering","multi-agent-automation"],healthcare:["web-engineering","rag-systems"],finance:["qa-testing","rag-systems","multi-agent-automation"],education:["mobile-apps","web-engineering"]};
const industryToWork: Record<string,string[]>={government:["railtrace"],healthcare:["medichain"],finance:[],education:["kucafe"]};
export function IndustryDetail() {
 const {id}=useParams(); const industry=INDUSTRIES.find((item)=>item.slug===id);
 if(!industry)return <div className="site-page min-h-screen flex flex-col items-center justify-center p-8 text-center"><h1 className="font-display text-3xl font-bold text-ink">Industry not found</h1><Link to="/industries" className="mt-6 inline-flex items-center gap-2 text-brand"><ArrowLeft size={14}/>Back</Link></div>;
 const relatedServices=SERVICES.filter((service)=>industryToServices[industry.slug]?.includes(service.slug)); const relatedWork=CASE_STUDIES.filter((project)=>industryToWork[industry.slug]?.includes(project.slug)); const jsonLd={"@context":"https://schema.org","@type":"WebPage",name:`${industry.title} Software Engineering — Kalpanaaaa`,description:industry.description,provider:{"@type":"Organization",name:"Kalpanaaaa Software Solutions Pvt. Ltd."}};
 return <div className="site-page min-h-screen"><SEO title={`${industry.title} Software Engineering | Kalpanaaaa Software Solutions`} description={industry.description} canonical={`https://kalpanaaasoftwaresolutions.in/industries/${industry.slug}`} jsonLd={jsonLd}/>
  <section className="relative overflow-hidden border-b border-line/70"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12 py-14 md:py-20"><Link to="/industries" className="inline-flex items-center gap-1.5 text-xs font-mono uppercase tracking-widest text-muted hover:text-brand mb-7"><ArrowLeft size={14}/>All industries</Link><div className="grid lg:grid-cols-[minmax(0,1fr)_minmax(400px,.9fr)] gap-10 items-center"><div><p className="eyebrow">Industry system</p><motion.h1 initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="mt-4 font-display text-4xl md:text-6xl font-extrabold tracking-tight text-ink">{industry.title}</motion.h1><p className="mt-2 text-lg text-brand font-semibold">{industry.short}</p><p className="mt-5 text-lg text-muted max-w-3xl leading-relaxed">{industry.description}</p></div><VisualScene className="detail-scene" variant={`industry-${industry.slug}`} title={`${industry.title} systems flow diagram`}/></div></div></section>
  <section className="py-16 md:py-20"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12"><SectionHeading eyebrow="Capabilities" title={`What we build for ${industry.title.toLowerCase()}`}/><ul className="grid gap-3 md:grid-cols-2 mt-8">{industry.features.map((feature,index)=><motion.li key={feature} initial={{opacity:0,x:-10}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:index*.04}} className="site-card flex items-start gap-3 p-4 rounded-xl"><CheckCircle2 size={18} className="text-brand mt-0.5 shrink-0"/><span className="text-sm text-ink">{feature}</span></motion.li>)}</ul></div></section>
  {relatedServices.length>0&&<section className="py-16 md:py-20 site-surface border-y border-line/70"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12"><SectionHeading eyebrow="Service fit" title="Capabilities mapped to this industry"/><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{relatedServices.map((service,index)=><ServiceCard key={service.slug} service={service} index={index}/>)}</div></div></section>}
  {relatedWork.length>0&&<section className="py-16 md:py-20"><div className="max-w-7xl mx-auto px-6 md:px-8 lg:px-12"><SectionHeading eyebrow="Selected work" title="Case studies in this industry"/><div className="mt-8 grid gap-6 md:grid-cols-2">{relatedWork.map((project,index)=><CaseStudyCard key={project.slug} project={project} index={index}/>)}</div></div></section>}
  <section className="py-20"><div className="max-w-4xl mx-auto px-6 text-center"><h2 className="font-display text-3xl md:text-4xl font-extrabold text-ink">Discuss a {industry.title} engagement</h2><Link to="/contact" className="button-primary mt-7 px-7 py-4 text-sm font-bold uppercase tracking-widest">Book a call <ArrowRight size={16}/></Link></div></section>
 </div>;
}
